import { Message } from '.'

export const mockMessages = (login: string): Array<Message> => [
  {
    from: login,
    to: 'Jonny',
    body: 'hi!',
    timestamp: 1641226830,
    id: '4',
    unread: true,
    status: 'OK',
  },
  {
    from: login,
    to: 'Howard',
    body: 'hi, man! how are you',
    timestamp: 1641226831,
    id: '5',
    unread: false,
    status: 'OK',
  },
  {
    from: 'Howard',
    to: login,
    body: 'hi, all good man, how are you',
    timestamp: 1641226932,
    id: '500',
    unread: false,
    status: 'OK',
  },
  {
    from: login,
    to: 'Howard',
    body: 'oh, its realy good, me too',
    timestamp: 1641226933,
    id: '6',
    unread: true,
    status: 'OK',
  },
  {
    from: login,
    to: 'Nick',
    body: 'hi!',
    timestamp: 1641226934,
    id: '3',
    unread: true,
    status: 'OK',
  },
  {
    from: login,
    to: 'Nick',
    body: 'hi!',
    timestamp: 1641226934,
    id: '3',
    unread: true,
    status: 'OK',
  },
  {
    from: login,
    to: 'Nick',
    body: 'hi!',
    timestamp: 1641226934,
    id: '3',
    unread: true,
    status: 'OK',
  },
  {
    from: login,
    to: 'Nick',
    body: 'hi!',
    timestamp: 1641226934,
    id: '3',
    unread: true,
    status: 'OK',
  },
  {
    from: login,
    to: 'Nick',
    body: 'hi!',
    timestamp: 1641226934,
    id: '3',
    unread: true,
    status: 'OK',
  },
  {
    from: login,
    to: 'Nick',
    body: 'hi!',
    timestamp: 1641226934,
    id: '3',
    unread: true,
    status: 'OK',
  },
  {
    from: login,
    to: 'Nick',
    body: 'hi!',
    timestamp: 1641226934,
    id: '3',
    unread: true,
    status: 'OK',
  },
  {
    from: login,
    to: 'Nick',
    body: 'hi!',
    timestamp: 1641226934,
    id: '3',
    unread: true,
    status: 'OK',
  },
  {
    from: login,
    to: 'Nick',
    body: 'hi!',
    timestamp: 1641226934,
    id: '3',
    unread: true,
    status: 'OK',
  },
  {
    from: login,
    to: 'Nick',
    body: 'hi!',
    timestamp: 1641226934,
    id: '3',
    unread: true,
    status: 'OK',
  },
  {
    from: login,
    to: 'Nick',
    body: 'hi!',
    timestamp: 1641226934,
    id: '3',
    unread: true,
    status: 'OK',
  },
  {
    from: login,
    to: 'Nick',
    body: 'hi!',
    timestamp: 1641226934,
    id: '3',
    unread: true,
    status: 'OK',
  },
  {
    from: login,
    to: 'Nick',
    body: 'hi!',
    timestamp: 1641226934,
    id: '3',
    unread: true,
    status: 'OK',
  },
  {
    from: 'Anon',
    to: login,
    body: 'hi!',
    timestamp: 1641226939,
    id: '32',
    unread: true,
    status: 'OK',
  },
]
