// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"github.com/google/uuid"
)

type Message struct {
	ID        uuid.UUID	`json:"id"` 
	From      string	`json:"from"`
	To        string	`json:"to"`
	Body      string	`json:"body"`
	Unread    bool 		`json:"unread"`
	Status    string	`json:"status"`
	Timestamp int64		`json:"timestamp"`
}

type PendingMessage struct {
	ID        uuid.UUID `json:"id"`
	From      string	`json:"from"`
	To        string	`json:"to"`
	Body      string	`json:"body"`
	Timestamp int64		`json:"timestamp"`
	Proceed   bool		`json:"proceed"`
}

type Status struct {
	ID          int32 	`json:"id"`
	Name        string	`json:"name"`
	Code        int32	`json:"code"`
	Description string	`json:"description"`
}
