# HTTP

### WatchMessages
GET http://localhost:8080/messages/watch?user=kotsmile&with=roma&offset=0

### AmountNewMessages
GET http://localhost:8080/messages/amount?user=kotsmile

### ReadMessages
GET http://localhost:8080/messages/read?user=kotsmile&with=roma

### GetChats 
GET http://localhost:8080/chats/get?user=kotsmile&offset=0


### SendMessage
POST http://localhost:8080/messages/send
Content-Type: application/json

{
    "id": "b8f757ff-43b3-488b-a84a-3c2ced37ac55",
    "from": "roma",
    "to": "kotsmile",
    "body": "hello man, how are you yoyo",
    "timestamp": 1641527346
}